#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Create ~/.local/bin if initial setup
mkdir -p $HOME/.local/bin
# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':' -)"

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"

# Dotfile directory
export MY_DOTFILES_DIR="$HOME/dotfiles"

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

export MACHINE=$machine

if [[ $MACHINE == "Mac" ]]; then
   # Load homebrew on shell satart
   eval "$(/opt/homebrew/bin/brew shellenv)"

   # add asdf homebrew path
   . /opt/homebrew/opt/asdf/libexec/asdf.sh
fi

